name: accessibility_service_example
description: "Demonstrates how to use the accessibility_service plugin."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  accessibility_service:
    # When depending on this package from a real application you should use:
    #   accessibility_service: ^x.y.z
    # See https://dart.dev/tools/pub/dependencies#version-constraints
    # The example app is bundled with the plugin so we use a path dependency on
    # the parent directory to use the current plugin's version.
    path: ../
  flutter_background_service: ^5.0.10
  flutter_local_notifications: ^18.0.1
  shared_preferences: ^2.3.3
  device_info_plus: ^11.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
